### ISSUE TITLE
Make a new single board shield, implementing components below 

### ISSUE THREAD

**Issue by pchou05** [namnik100/TARC#2]
https://www.digikey.com/en/products/detail/tdk-invensense/ICM-20602/5872870

some type of oscillator?

4 pwm ports

level shifters will be needed to convert from seed xiao 5v logic to 3.3v logic
consider something like this: https://www.digikey.com/en/products/detail/texas-instruments/TXS0108EPWR/1775302

**Comment by stygmatic** [comment]
Added the icm 20602 and converter
